In [3]:
import pandas as pd
import numpy as np

In [4]:
zeros_array = np.zeros(10)
zeros_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [6]:
ones_array = np.ones(10)
ones_array

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [8]:
constant_array = np.full(10, 3)
constant_array

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3])

In [9]:
np.zeros((5,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [10]:
np.linspace(0, 100, 11)

array([  0.,  10.,  20.,  30.,  40.,  50.,  60.,  70.,  80.,  90., 100.])

In [12]:
n = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
n

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [15]:
n[0,1] = 20
n

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9]])

In [24]:
np.random.seed(2)
random_array = np.random.rand(5, 2) 
random_array

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [29]:
normal_distribution = np.random.randn(5, 2)
normal_distribution
random_integers = np.random.randint(low=0, high=100, size=(5, 2))
random_integers

array([[50, 73],
       [ 7, 49],
       [82,  1],
       [79, 91],
       [96, 49]], dtype=int32)